### ISSUE TITLE
Dictionaries can't be loaded (<built-in function unitex_load_persistent_dictionary> returned NULL without setting an error)

### ISSUE THREAD

**Issue by milos-simic** [patwat/python-unitex#3]
When I try to instantiate `UnitexProcessor`, dictionaries can't get loaded. This is my code:

```
import yaml
from unitex.processor import UnitexProcessor
from unitex.config import UnitexConfig

config_file = "nlp_layer/serbian.yaml"

with open(config_file, "r") as f:
	options = yaml.load(f, Loader=yaml.FullLoader)

config = UnitexConfig()
config.load(options)

processor = UnitexProcessor(config)
```

I'm running Unitex on a 64-bit machine with Ubuntu 16.04 LTS as its operating system, under python 3.5. All the tests went fine after installation. The error I'm receiving now is:

```
Traceback (most recent call last):
  File "mwu.py", line 15, in <module>
    processor = UnitexProcessor(config)
  File "/usr/local/lib/python3.5/dist-packages/unitex/processor.py", line 56, in __init__
    self._load()
  File "/usr/local/lib/python3.5/dist-packages/unitex/processor.py", line 96, in _load
    _object = load_persistent_dictionary(dictionary)
  File "/usr/local/lib/python3.5/dist-packages/unitex/resources.py", line 30, in load_persistent_dictionary
    return _unitex.unitex_load_persistent_dictionary(path)
SystemError: <built-in function unitex_load_persistent_dictionary> returned NULL without setting an error
```

The file `serbian.yaml` is as follows:
```
global:
  debug: 0
  log: null
  persistence: true
  verbose: 0
  virtualization: true
resources:
  alphabet: /home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Alphabet.txt
  alphabet-sorted: /home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Alphabet_sort.txt
  dictionaries:
  - !!python/unicode '/home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Dela/latdelaf-SrpskiU.bin'
  - !!python/unicode '/home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Dela/latDelacf-SrpskiU.bin'
  - !!python/unicode '/home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Dela/latDelacf-NepromU.bin'
  - !!python/unicode '/home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Dela/NewBrojSlovima.fst2'
  - !!python/unicode '/home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Dela/NewBrojSlovima_norm-z.fst2'
  language: sr
  replace: /home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Graphs/Preprocessing/Replace/Replace.fst2
  sentence: /home/milos/upitija/Unitex-GramLab-3.1/Serbian-Latin/Graphs/Preprocessing/Sentence/Sentence.fst2
tools:
  check_dic:
    no_space_warning: false
    strict: false
  compress:
    flip: false
    output: null
    semitic: false
    version: v2
  concord:
    directory: null
    font: null
    fontsize: null
    format: text
    left: '0'
    offsets: null
    only_ambiguous: false
    only_matches: false
    right: '0'
    script: null
    sort: TO
    thai: false
    unxmlize: null
  dico:
    arabic_rules: null
    korean: false
    morpho: null
    raw: null
    semitic: false
  extract:
    non_matching_sentences: false
  fst2txt:
    merge: true
    start_on_space: false
    word_by_word: false
  grf2fst2:
    char_by_char: false
    check_variables: true
    debug: false
    loop_check: false
    named_repository: null
    no_empty_graph_warning: false
    pkgdir: null
    silent_grf_name: true
    tfst_check: false
  locate:
    ambiguous_outputs: true
    arabic_rules: null
    char_by_char: false
    korean: false
    match_mode: longest
    morpho: null
    negation_operator: tilde
    number_of_matches: null
    output_mode: merge
    protect_dic_chars: true
    sntdir: null
    start_on_space: false
    stop_token_count: null
    variable: null
    variable_error: ignore
  normalize:
    input_offsets: null
    no_carriage_return: false
    no_separator_normalization: false
    output_offsets: null
    replacement_rules: null
  sort_txt:
    duplicates: false
    factorize_inflectional_codes: false
    line_info: null
    reverse: false
    sort_order: null
    thai: false
  tokenize:
    char_by_char: false
    input_offsets: null
    output_offsets: null
    tokens: null
  txt2tfst:
    clean: false
    korean: false
    normalization_grammar: null
    tagset: null
```

The configuration file was generated automatically. All the dictionaries are present at the locations specified in the configuration file.

**Comment by milos-simic** [comment]
After removing `fst2` dictionaries from the configuration file, I was able to run everything successfully.
